Repository wecode-bootcamp-korea/23-1st-TangoPlate-frontend, pull requests merged in 2021-08, with the labels that each got.

#1 [23기 김명성] MODIFY : 수정사항 반영 / ADD : 슬라이드 기능 구현, Nav 추가
  package-lock.json
  package.json
  public/data/listInfoData.json
  public/data/mockdata.json
  public/data/shopInfoData.json
  public/images/beyonce.jpeg
  public/images/ex_food.jpg
  public/images/hot_dog.jpg
  public/images/tangoLogo.png
  public/index.html
  src/Routes.js
  src/pages/Main/EatDealContainer/EatDealContainer.js
  src/pages/Main/EatDealContainer/EatDealContainer.scss
  src/pages/Main/ListInfo/ListInfo.js
  src/pages/Main/ListInfo/ListInfo.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/Nav/Nav.js
  src/pages/Main/Nav/Nav.scss
  src/pages/Main/SearchFocus/SearchFocus.js
  src/pages/Main/SearchFocus/SearchFocus.scss
  src/pages/Main/SearchForm/SearchForm.js
  src/pages/Main/SearchForm/SearchForm.scss
  src/pages/Main/ShopListContainer/ShopListContainer.js
  src/pages/Main/ShopListContainer/ShopListContainer.scss
  src/pages/Main/SlideButton/SlideButton.js
  src/pages/Main/SlideButton/SlideButton.scss
  src/pages/Main/images/ex_food.jpg
  src/pages/Main/images/hot_dog.jpg
  src/pages/Main/style/variable.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#6 [23기 김명성] ADD : 검색 기능 구현
  README.md
  src/pages/Main/Main.js
  src/pages/Main/SearchForm/SearchForm.js
  src/pages/Main/SearchForm/SearchForm.scss
Labels: Status: Accepted

#5 [23기 최정민] MODIFY:코드리뷰 수정
  .eslintrc
  .prettierrc
  .vscode/launch.json
  public/data/restaurantdetail.json
  public/images/shopDetail/1.jpeg
  public/images/shopDetail/10.svg
  public/images/shopDetail/11.svg
  public/images/shopDetail/2.jpeg
  public/images/shopDetail/3.jpeg
  public/images/shopDetail/30.svg
  public/images/shopDetail/31.svg
  public/images/shopDetail/4.jpeg
  public/images/shopDetail/50.svg
  public/images/shopDetail/51.svg
  public/images/shopDetail/7.png
  public/images/shopDetail/tangoLogo.png
  public/images/shopDetail/write.png
  public/images/shopDetail/도현님.jpg
  public/images/shopDetail/도현님.png
  public/index.html
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/config.js
  src/pages/Login/InputContainer/Andline/Andline.js
  src/pages/Login/InputContainer/Andline/Andline.scss
  src/pages/Login/InputContainer/Button/Button.js
  src/pages/Login/InputContainer/Button/Button.scss
  src/pages/Login/InputContainer/InputBox/InputBox.js
  src/pages/Login/InputContainer/InputBox/InputBox.scss
  src/pages/Login/InputContainer/InputContainer.js
  src/pages/Login/InputContainer/InputContainer.scss
  src/pages/Login/Sign.scss
  src/pages/Login/SignInUser.js
  src/pages/Login/SignInUser.scss
  src/pages/Login/Signin.js
  src/pages/Login/Signup.js
  src/pages/Main/Main.js
  src/pages/ShopDetail/RestaurantInfo/RestaurantInfo.js
  src/pages/ShopDetail/RestaurantInfo/RestaurantInfo.scss
  src/pages/ShopDetail/RestaurantReview/RestaurantReview.js
  src/pages/ShopDetail/RestaurantReview/RestaurantReview.scss
  src/pages/ShopDetail/ReviewWritingPage/ReviewGradeButton/ReviewGradeButton.js
  src/pages/ShopDetail/ReviewWritingPage/ReviewGradeButton/ReviewGradeButton.scss
  src/pages/ShopDetail/ReviewWritingPage/ReviewWritingPage.js
  src/pages/ShopDetail/ReviewWritingPage/ReviewWritingPage.scss
  src/pages/ShopDetail/ShopDetail.js
  src/pages/ShopDetail/ShopDetail.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#4 [23기 최정민] ADD : nav, 로그인, 회원가입
  kdfj
  public/index.html
  src/Routes.js
  src/config.js
  src/pages/Login/SignInUser.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청
